name: flutter_highlight
description: Syntax highlighting widget for Flutter with lots of languages and themes support.
version: 0.6.0+1
author: Rongjian Zhang <pd4d10@gmail.com>
homepage: https://github.com/git-touch/highlight

publish_to: none

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  highlight:
    path: ../highlight

dev_dependencies:
  flutter_test:
    sdk: flutter
# dependency_overrides:
#   highlight:
#     path: ../highlight
