name: highlight
description: Syntax highlighting for Dart with lots of languages and themes support.
version: 0.4.1
author: Rongjian Zhang <pd4d10@gmail.com>
homepage: https://github.com/pd4d10/highlight

environment:
  sdk: ">=2.3.0 <3.0.0"

dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.6.0
  path: ^1.6.0
